clustershell: rpm: remove python2 macro defs
These definitions are useless in fairly recent build environment and
even cause errors at build time on el8:

  error: attempt to use unversioned python, define %__python to
  /usr/bin/python2 or /usr/bin/python3 explicitly
  error: Macro %python2_sitelib failed to expand
  error: line 5: %{!?python2_sitelib: %global python2_sitelib
  %{python_sitelib}}